import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./global.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode
    modal: React.ReactNode
  }>,
) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {props.children}
        {props.modal}
        <div id="modal-root" />
      </body>
    </html>
  )
}
