import { Toaster } from "@/components/ui/sonner"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./global.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode
    modal: React.ReactNode
  }>,
) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>{props.children}</main>
        {props.modal}
        <Toaster
          // closeButton
          richColors
          toastOptions={{
            classNames: {
              toast: "items-start leading-[20px]",
              icon: "mt-[3px]",
              title: "leading-[22px] text-[16px] break-all",
              description: "leading-[20px] max-h-[150px] overflow-y-auto break-all",
            },
          }}
          visibleToasts={Infinity}
          position="top-right"
        />
      </body>
    </html>
  )
}
